# Generated by Django 5.1.7 on 2025-03-27 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_transaccion_cantidad_transaccion_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='producto',
            new_name='vaper',
        ),
    ]
